### ISSUE TITLE
Template precompile

### ISSUE THREAD

**Issue by jcblw** [rendrjs/rendr-app-template#21]
Ive tried with two Mac OSX 10.8.0 & 10.8.2 to install the app, and recieved the same issue from express.

```
500 Template was precompiled with a newer version of Handlebars than the current runtime. Please update your runtime to a newer version (>= 1.0.0-rc.4).
```

We swap out the hack with the version listed above, in the rendr node_module `package.json` and then Handlbars does not get included correctly so i get this error.

```
Uncaught TypeError: Object #<Object> has no method 'registerHelper'
```

Thanks in advance

**Comment by Legogris** [comment]
Same here - culprit seems to be conflicting versions of handlebars in grunt-contrib-handlebars and rendr. I got the server working by getting a more recent version of handlebars (as indicated by the error message) into rendr and applying the hack made in the one downloading to rendr (namely, paste this file: https://raw.github.com/spikebrehm/handlebars.js/0687c7016c62122ab160a8683817a931b03354ad/lib/handlebars/compiler/parser.js into the handlebars module). After that Handlebars is not loaded correctly at the client, though. Would be nice if Spike could look into this!

**Comment by spikebrehm** [comment]
Doh! Sorry about that, all.  Fix is here:

https://github.com/airbnb/rendr-app-template/commit/94e1ed033c2c1e3a0fede94bf4c2ccf3baa88cee

This silliness of using a patched version of Handlebars should be resolved as soon as I get my PR merged into the Handlebars repo for better support of Handlebars in non-Browserify client-side CommonJS environments.

...or just switch to Browserify.

**Comment by jcblw** [comment]
thanks a ton :+1:
