### ISSUE TITLE
Handlebars precompiled versioning error

### ISSUE THREAD

**Issue by trueadm** [rendrjs/rendr-app-template#38]
I get this error when attempting to connect for the first time:

<pre>500 Template was precompiled with an older version of Handlebars than the current runtime. Please update your precompiler to a newer version (>= 1.0.0) or downgrade your runtime to an older version (== 1.0.0-rc.3).</pre>

Can I can resolve this without hacking about the different NPM modules? Thanks.

**Comment by spikebrehm** [comment]
Hi, sorry about that.  I was just in the middle of tweaking Handlebars versions to support Handlebars 1.0.12 (it's actually a fork of Handlebars that includes a commit that's in master to support CommonJS out of the box; unfortunately though it's in master, the maintainers haven't published that version to NPM).

Try this: pull down the latest master from this repo, and then run:

``` bash
rm -rf node_modules
npm install
```

That should fix it.
