### ISSUE TITLE
Broken links in README

### ISSUE THREAD

**Issue by neojski** [rendrjs/rendr-app-template#43]
Have a look here:

https://github.com/airbnb/rendr-app-template#the-view-hierarchy

links:
https://github.com/airbnb/rendr-app-template/blob/master/app/templates/users_show_view.hbs
https://github.com/airbnb/rendr-app-template/blob/master/app/views/users_show_view.js

are broken.

**Comment by spikebrehm** [comment]
Thanks! Fixed here: a5fe7b664412c1e5b66f7caaa01aa65e42154de5
