### ISSUE TITLE
Error: npm install rendr-app-template 

### ISSUE THREAD

**Issue by NourSammour** [rendrjs/rendr-app-template#5]
npm ERR! command "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nod
ejs\node_modules\npm\bin\npm-cli.js" "install" "rendr-app-template"

i am working on windows 7 
i try "run as administrator"
but still not work .... please help me

**Comment by spikebrehm** [comment]
We're going to need more debugging info than that to help you out!  Is there not a stacktrace or anything?
