### ISSUE TITLE
npm install errors (ubuntu 12.04)

### ISSUE THREAD

**Issue by haknick** [rendrjs/rendr-app-template#53]
I get the following errors when I run npm install:

vagrant@precise32:/home/website/nodejs/rendr-try2/rendr-app-template$ npm install
npm http GET https://registry.npmjs.org/grunt-contrib-stylus
npm http GET https://registry.npmjs.org/express
npm http GET https://registry.npmjs.org/rendr-handlebars/0.0.5
npm http GET https://registry.npmjs.org/js-yaml
npm http GET https://registry.npmjs.org/grunt
npm http GET https://registry.npmjs.org/nodemon
npm http GET https://registry.npmjs.org/grunt-rendr-stitch
npm http GET https://registry.npmjs.org/mocha
npm http 200 https://registry.npmjs.org/rendr-handlebars/0.0.5
npm http GET https://registry.npmjs.org/rendr-handlebars/-/rendr-handlebars-0.0.5.tgz
npm http 200 https://registry.npmjs.org/grunt-contrib-stylus
npm http 200 https://registry.npmjs.org/js-yaml
npm http 200 https://registry.npmjs.org/grunt
npm http 200 https://registry.npmjs.org/grunt-rendr-stitch
npm http 200 https://registry.npmjs.org/nodemon
npm http 200 https://registry.npmjs.org/mocha
npm http 200 https://registry.npmjs.org/express
npm http GET https://registry.npmjs.org/grunt-contrib-stylus/-/grunt-contrib-stylus-0.5.1.tgz
npm http GET https://registry.npmjs.org/js-yaml/-/js-yaml-2.1.3.tgz
npm http GET https://registry.npmjs.org/grunt/-/grunt-0.4.1.tgz
npm http GET https://registry.npmjs.org/grunt-rendr-stitch/-/grunt-rendr-stitch-0.0.8.tgz
npm http GET https://registry.npmjs.org/nodemon/-/nodemon-0.7.10.tgz
npm http GET https://registry.npmjs.org/mocha/-/mocha-1.9.0.tgz
npm http GET https://registry.npmjs.org/express/-/express-3.4.3.tgz
npm http 200 https://registry.npmjs.org/rendr-handlebars/-/rendr-handlebars-0.0.5.tgz
npm http 200 https://registry.npmjs.org/nodemon/-/nodemon-0.7.10.tgz
npm http 200 https://registry.npmjs.org/grunt-contrib-stylus/-/grunt-contrib-stylus-0.5.1.tgz
npm http 200 https://registry.npmjs.org/grunt/-/grunt-0.4.1.tgz
npm http 200 https://registry.npmjs.org/mocha/-/mocha-1.9.0.tgz
npm http 200 https://registry.npmjs.org/grunt-rendr-stitch/-/grunt-rendr-stitch-0.0.8.tgz
npm http 200 https://registry.npmjs.org/js-yaml/-/js-yaml-2.1.3.tgz
npm http 200 https://registry.npmjs.org/express/-/express-3.4.3.tgz
npm http GET https://registry.npmjs.org/rendr
npm http GET https://registry.npmjs.org/coffee-script
npm http GET https://registry.npmjs.org/async
npm http 200 https://registry.npmjs.org/rendr
npm http GET https://registry.npmjs.org/rendr/-/rendr-0.4.10.tgz
npm http 200 https://registry.npmjs.org/coffee-script
npm http 200 https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/coffee-script/-/coffee-script-1.6.3.tgz
npm http 200 https://registry.npmjs.org/rendr/-/rendr-0.4.10.tgz
npm http GET https://registry.npmjs.org/async/-/async-0.2.9.tgz
npm http 200 https://registry.npmjs.org/coffee-script/-/coffee-script-1.6.3.tgz
npm http 200 https://registry.npmjs.org/async/-/async-0.2.9.tgz
npm http GET https://registry.npmjs.org/mkdirp/0.3.5
npm http GET https://registry.npmjs.org/buffer-crc32/0.2.1
npm http GET https://registry.npmjs.org/cookie/0.1.0
npm http GET https://registry.npmjs.org/fresh/0.2.0
npm http GET https://registry.npmjs.org/methods/0.0.1
npm http GET https://registry.npmjs.org/send/0.1.4
npm http GET https://registry.npmjs.org/cookie-signature/1.0.1
npm http GET https://registry.npmjs.org/connect/2.10.1
npm http GET https://registry.npmjs.org/commander/1.3.2
npm http GET https://registry.npmjs.org/range-parser/0.0.4
npm http GET https://registry.npmjs.org/stylus
npm http GET https://registry.npmjs.org/nib
npm http 200 https://registry.npmjs.org/methods/0.0.1
npm http 200 https://registry.npmjs.org/buffer-crc32/0.2.1
npm http 200 https://registry.npmjs.org/mkdirp/0.3.5
npm http 200 https://registry.npmjs.org/send/0.1.4
npm http 200 https://registry.npmjs.org/fresh/0.2.0
npm http 200 https://registry.npmjs.org/cookie/0.1.0
npm http 200 https://registry.npmjs.org/cookie-signature/1.0.1
npm http GET https://registry.npmjs.org/methods/-/methods-0.0.1.tgz
npm http 200 https://registry.npmjs.org/range-parser/0.0.4
npm http 200 https://registry.npmjs.org/commander/1.3.2
npm http 200 https://registry.npmjs.org/connect/2.10.1
npm http GET https://registry.npmjs.org/buffer-crc32/-/buffer-crc32-0.2.1.tgz
npm http 200 https://registry.npmjs.org/nib
npm http GET https://registry.npmjs.org/mkdirp/-/mkdirp-0.3.5.tgz
npm http GET https://registry.npmjs.org/send/-/send-0.1.4.tgz
npm http GET https://registry.npmjs.org/fresh/-/fresh-0.2.0.tgz
npm http 200 https://registry.npmjs.org/stylus
npm http GET https://registry.npmjs.org/cookie/-/cookie-0.1.0.tgz
npm http GET https://registry.npmjs.org/cookie-signature/-/cookie-signature-1.0.1.tgz
npm http GET https://registry.npmjs.org/range-parser/-/range-parser-0.0.4.tgz
npm http GET https://registry.npmjs.org/commander/-/commander-1.3.2.tgz
npm http GET https://registry.npmjs.org/connect/-/connect-2.10.1.tgz
npm http GET https://registry.npmjs.org/nib/-/nib-0.9.2.tgz
npm http GET https://registry.npmjs.org/stylus/-/stylus-0.32.1.tgz
npm http GET https://registry.npmjs.org/grunt-lib-contrib
npm http 200 https://registry.npmjs.org/methods/-/methods-0.0.1.tgz
npm http 200 https://registry.npmjs.org/cookie/-/cookie-0.1.0.tgz
npm http 200 https://registry.npmjs.org/cookie-signature/-/cookie-signature-1.0.1.tgz
npm http 200 https://registry.npmjs.org/buffer-crc32/-/buffer-crc32-0.2.1.tgz
npm http 200 https://registry.npmjs.org/range-parser/-/range-parser-0.0.4.tgz
npm http 200 https://registry.npmjs.org/commander/-/commander-1.3.2.tgz
npm http 200 https://registry.npmjs.org/fresh/-/fresh-0.2.0.tgz
npm http 200 https://registry.npmjs.org/send/-/send-0.1.4.tgz
npm http 200 https://registry.npmjs.org/mkdirp/-/mkdirp-0.3.5.tgz
npm http 200 https://registry.npmjs.org/nib/-/nib-0.9.2.tgz
npm http 200 https://registry.npmjs.org/connect/-/connect-2.10.1.tgz
npm http 200 https://registry.npmjs.org/stylus/-/stylus-0.32.1.tgz
npm http 200 https://registry.npmjs.org/grunt-lib-contrib
npm WARN excluding symbolic link test/fixtures/link -> default
npm http GET https://registry.npmjs.org/grunt-lib-contrib/-/grunt-lib-contrib-0.5.3.tgz
npm http GET https://registry.npmjs.org/argparse
npm http GET https://registry.npmjs.org/esprima
npm http 200 https://registry.npmjs.org/grunt-lib-contrib/-/grunt-lib-contrib-0.5.3.tgz
npm http 200 https://registry.npmjs.org/esprima
npm http 200 https://registry.npmjs.org/argparse
npm http GET https://registry.npmjs.org/esprima/-/esprima-1.0.4.tgz
npm http GET https://registry.npmjs.org/argparse/-/argparse-0.1.15.tgz
npm http 200 https://registry.npmjs.org/esprima/-/esprima-1.0.4.tgz
npm http 200 https://registry.npmjs.org/argparse/-/argparse-0.1.15.tgz
npm http GET https://registry.npmjs.org/mkdirp/0.3.3
npm http GET https://registry.npmjs.org/ms/0.3.0
npm http GET https://registry.npmjs.org/commander/0.6.1
npm http GET https://registry.npmjs.org/growl
npm http GET https://registry.npmjs.org/jade/0.26.3
npm http GET https://registry.npmjs.org/diff/1.0.2
npm http 200 https://registry.npmjs.org/mkdirp/0.3.3
npm http GET https://registry.npmjs.org/dateformat/1.0.2-1.2.3
npm http GET https://registry.npmjs.org/eventemitter2
npm http GET https://registry.npmjs.org/nopt
npm http GET https://registry.npmjs.org/findup-sync
npm http GET https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/glob
npm http GET https://registry.npmjs.org/lodash
npm http GET https://registry.npmjs.org/hooker
npm http GET https://registry.npmjs.org/iconv-lite
npm http GET https://registry.npmjs.org/minimatch
npm http GET https://registry.npmjs.org/underscore.string
npm http GET https://registry.npmjs.org/which
npm http GET https://registry.npmjs.org/colors
npm http 200 https://registry.npmjs.org/ms/0.3.0
npm http 200 https://registry.npmjs.org/growl
npm http 200 https://registry.npmjs.org/diff/1.0.2
npm http 200 https://registry.npmjs.org/commander/0.6.1
npm http 200 https://registry.npmjs.org/jade/0.26.3
npm http GET https://registry.npmjs.org/js-yaml
npm http GET https://registry.npmjs.org/coffee-script
npm http 200 https://registry.npmjs.org/dateformat/1.0.2-1.2.3
npm http GET https://registry.npmjs.org/mkdirp/-/mkdirp-0.3.3.tgz
npm http 200 https://registry.npmjs.org/findup-sync
npm http 200 https://registry.npmjs.org/rimraf
npm http 200 https://registry.npmjs.org/nopt
npm http 200 https://registry.npmjs.org/eventemitter2
npm http GET https://registry.npmjs.org/commander/-/commander-0.6.1.tgz
npm http 200 https://registry.npmjs.org/hooker
npm http GET https://registry.npmjs.org/growl/-/growl-1.7.0.tgz
npm http GET https://registry.npmjs.org/ms/-/ms-0.3.0.tgz
npm http GET https://registry.npmjs.org/diff/-/diff-1.0.2.tgz
npm http GET https://registry.npmjs.org/jade/-/jade-0.26.3.tgz
npm http 200 https://registry.npmjs.org/minimatch
npm http 200 https://registry.npmjs.org/iconv-lite
npm http 200 https://registry.npmjs.org/glob
npm http 200 https://registry.npmjs.org/lodash
npm http 200 https://registry.npmjs.org/underscore.string
npm http 200 https://registry.npmjs.org/which
npm http 200 https://registry.npmjs.org/colors
npm http 304 https://registry.npmjs.org/js-yaml
npm http 304 https://registry.npmjs.org/coffee-script
npm http GET https://registry.npmjs.org/dateformat/-/dateformat-1.0.2-1.2.3.tgz
npm http GET https://registry.npmjs.org/findup-sync/-/findup-sync-0.1.2.tgz
npm http GET https://registry.npmjs.org/rimraf/-/rimraf-2.0.3.tgz
npm http GET https://registry.npmjs.org/nopt/-/nopt-1.0.10.tgz
npm http GET https://registry.npmjs.org/eventemitter2/-/eventemitter2-0.4.13.tgz
npm http GET https://registry.npmjs.org/hooker/-/hooker-0.2.3.tgz
npm http GET https://registry.npmjs.org/minimatch/-/minimatch-0.2.12.tgz
npm http GET https://registry.npmjs.org/iconv-lite/-/iconv-lite-0.2.11.tgz
npm http GET https://registry.npmjs.org/glob/-/glob-3.1.21.tgz
npm http 200 https://registry.npmjs.org/mkdirp/-/mkdirp-0.3.3.tgz
npm http GET https://registry.npmjs.org/lodash/-/lodash-0.9.2.tgz
npm http GET https://registry.npmjs.org/underscore.string/-/underscore.string-2.2.1.tgz
npm http GET https://registry.npmjs.org/which/-/which-1.0.5.tgz
npm http GET https://registry.npmjs.org/js-yaml/-/js-yaml-2.0.5.tgz
npm http GET https://registry.npmjs.org/colors/-/colors-0.6.2.tgz
npm http GET https://registry.npmjs.org/coffee-script/-/coffee-script-1.3.3.tgz
npm http 200 https://registry.npmjs.org/commander/-/commander-0.6.1.tgz
npm http 200 https://registry.npmjs.org/jade/-/jade-0.26.3.tgz
npm http 200 https://registry.npmjs.org/growl/-/growl-1.7.0.tgz
npm http 200 https://registry.npmjs.org/ms/-/ms-0.3.0.tgz
npm http 200 https://registry.npmjs.org/dateformat/-/dateformat-1.0.2-1.2.3.tgz
npm http 200 https://registry.npmjs.org/diff/-/diff-1.0.2.tgz
npm http 200 https://registry.npmjs.org/findup-sync/-/findup-sync-0.1.2.tgz
npm http 200 https://registry.npmjs.org/rimraf/-/rimraf-2.0.3.tgz
npm http 200 https://registry.npmjs.org/nopt/-/nopt-1.0.10.tgz
npm http 200 https://registry.npmjs.org/eventemitter2/-/eventemitter2-0.4.13.tgz
npm http 200 https://registry.npmjs.org/hooker/-/hooker-0.2.3.tgz
npm http 200 https://registry.npmjs.org/minimatch/-/minimatch-0.2.12.tgz
npm http 200 https://registry.npmjs.org/iconv-lite/-/iconv-lite-0.2.11.tgz
npm http 200 https://registry.npmjs.org/underscore.string/-/underscore.string-2.2.1.tgz
npm http 200 https://registry.npmjs.org/glob/-/glob-3.1.21.tgz
npm http 200 https://registry.npmjs.org/lodash/-/lodash-0.9.2.tgz
npm http 200 https://registry.npmjs.org/which/-/which-1.0.5.tgz
npm http 200 https://registry.npmjs.org/js-yaml/-/js-yaml-2.0.5.tgz
npm http 200 https://registry.npmjs.org/colors/-/colors-0.6.2.tgz
npm http 200 https://registry.npmjs.org/coffee-script/-/coffee-script-1.3.3.tgz
npm http GET https://registry.npmjs.org/zlib-browserify/0.0.1
npm http 200 https://registry.npmjs.org/zlib-browserify/0.0.1
npm http GET https://registry.npmjs.org/zlib-browserify/-/zlib-browserify-0.0.1.tgz
npm http 200 https://registry.npmjs.org/zlib-browserify/-/zlib-browserify-0.0.1.tgz
npm http GET https://registry.npmjs.org/optimist
npm http GET https://registry.npmjs.org/uglify-js
npm http GET https://registry.npmjs.org/npm/1.3.4
npm http GET https://registry.npmjs.org/backbone/1.0.0
npm http GET https://registry.npmjs.org/qs/0.5.1
npm http GET https://registry.npmjs.org/rendr-handlebars/0.0.6
npm http GET https://registry.npmjs.org/validator/0.4.21
npm http GET https://registry.npmjs.org/express
npm http 200 https://registry.npmjs.org/optimist
npm http 200 https://registry.npmjs.org/rendr-handlebars/0.0.6
npm http GET https://registry.npmjs.org/optimist/-/optimist-0.3.7.tgz
npm http GET https://registry.npmjs.org/rendr-handlebars/-/rendr-handlebars-0.0.6.tgz
npm http 200 https://registry.npmjs.org/validator/0.4.21
npm http 200 https://registry.npmjs.org/uglify-js
npm http 304 https://registry.npmjs.org/express
npm http 200 https://registry.npmjs.org/qs/0.5.1
npm http 200 https://registry.npmjs.org/backbone/1.0.0
npm http 200 https://registry.npmjs.org/npm/1.3.4
npm http GET https://registry.npmjs.org/validator/-/validator-0.4.21.tgz
npm http GET https://registry.npmjs.org/uglify-js/-/uglify-js-2.3.6.tgz
npm http GET https://registry.npmjs.org/express/-/express-3.0.6.tgz
npm http GET https://registry.npmjs.org/qs/-/qs-0.5.1.tgz
npm http GET https://registry.npmjs.org/backbone/-/backbone-1.0.0.tgz
npm http GET https://registry.npmjs.org/npm/-/npm-1.3.4.tgz
npm http 200 https://registry.npmjs.org/optimist/-/optimist-0.3.7.tgz
npm http 200 https://registry.npmjs.org/rendr-handlebars/-/rendr-handlebars-0.0.6.tgz
npm http 200 https://registry.npmjs.org/qs/-/qs-0.5.1.tgz
npm http 200 https://registry.npmjs.org/backbone/-/backbone-1.0.0.tgz
npm http 200 https://registry.npmjs.org/npm/-/npm-1.3.4.tgz
npm http 200 https://registry.npmjs.org/uglify-js/-/uglify-js-2.3.6.tgz
npm http 200 https://registry.npmjs.org/validator/-/validator-0.4.21.tgz
npm http 200 https://registry.npmjs.org/express/-/express-3.0.6.tgz
npm http GET https://registry.npmjs.org/stylus
npm http 304 https://registry.npmjs.org/stylus
npm http GET https://registry.npmjs.org/stylus/-/stylus-0.31.0.tgz
npm http 200 https://registry.npmjs.org/stylus/-/stylus-0.31.0.tgz
npm ERR! Error: UNKNOWN, symlink '../coffee-script/bin/coffee'
npm ERR! If you need help, you may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com

npm ERR! System Linux 3.2.0-23-generic-pae
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /home/website/nodejs/rendr-try2/rendr-app-template
npm ERR! node -v v0.10.21
npm ERR! npm -v 1.3.11
npm ERR! path ../coffee-script/bin/coffee
npm ERR! code UNKNOWN
npm ERR! errno -1
npm http GET https://registry.npmjs.org/mime
npm http GET https://registry.npmjs.org/keypress
npm http 200 https://registry.npmjs.org/mime
npm http GET https://registry.npmjs.org/mime/-/mime-1.2.11.tgz
npm http 200 https://registry.npmjs.org/keypress
npm http GET https://registry.npmjs.org/keypress/-/keypress-0.1.0.tgz
npm http GET https://registry.npmjs.org/mkdirp/0.3.0
npm http GET https://registry.npmjs.org/cssom
npm http GET https://registry.npmjs.org/mkdirp
npm http 200 https://registry.npmjs.org/mime/-/mime-1.2.11.tgz
npm http 200 https://registry.npmjs.org/keypress/-/keypress-0.1.0.tgz
npm http 200 https://registry.npmjs.org/mkdirp/0.3.0
npm http GET https://registry.npmjs.org/mkdirp/-/mkdirp-0.3.0.tgz
npm http 200 https://registry.npmjs.org/mkdirp
npm http 200 https://registry.npmjs.org/cssom
npm http GET https://registry.npmjs.org/cssom/-/cssom-0.2.5.tgz
npm http 200 https://registry.npmjs.org/mkdirp/-/mkdirp-0.3.0.tgz
npm http 200 https://registry.npmjs.org/cssom/-/cssom-0.2.5.tgz
npm http GET https://registry.npmjs.org/multiparty/2.2.0
npm http GET https://registry.npmjs.org/pause/0.0.1
npm http GET https://registry.npmjs.org/bytes/0.2.0
npm http GET https://registry.npmjs.org/qs/0.6.5
npm http GET https://registry.npmjs.org/uid2/0.0.2
npm http GET https://registry.npmjs.org/raw-body/0.0.3
npm http GET https://registry.npmjs.org/negotiator/0.2.8
npm http 200 https://registry.npmjs.org/uid2/0.0.2
npm http 200 https://registry.npmjs.org/multiparty/2.2.0
npm http 200 https://registry.npmjs.org/pause/0.0.1
npm http 200 https://registry.npmjs.org/raw-body/0.0.3
npm http 200 https://registry.npmjs.org/qs/0.6.5
npm http 200 https://registry.npmjs.org/negotiator/0.2.8
npm http 200 https://registry.npmjs.org/bytes/0.2.0
npm http GET https://registry.npmjs.org/uid2/-/uid2-0.0.2.tgz
npm http GET https://registry.npmjs.org/multiparty/-/multiparty-2.2.0.tgz
npm http GET https://registry.npmjs.org/qs/-/qs-0.6.5.tgz
npm http GET https://registry.npmjs.org/pause/-/pause-0.0.1.tgz
npm http GET https://registry.npmjs.org/raw-body/-/raw-body-0.0.3.tgz
npm http GET https://registry.npmjs.org/negotiator/-/negotiator-0.2.8.tgz
npm http GET https://registry.npmjs.org/bytes/-/bytes-0.2.0.tgz
npm ERR! error rolling back Error: UNKNOWN, unlink '/home/website/nodejs/rendr-try2/rendr-app-template/node_modules/grunt/node_modules/lodash/lod
ash.js'
npm ERR! error rolling back  grunt@0.4.1 { [Error: UNKNOWN, unlink '/home/website/nodejs/rendr-try2/rendr-app-template/node_modules/grunt/node_mo
dules/lodash/lodash.js']
npm ERR! error rolling back   errno: -1,
npm ERR! error rolling back   code: 'UNKNOWN',
npm ERR! error rolling back   path: '/home/website/nodejs/rendr-try2/rendr-app-template/node_modules/grunt/node_modules/lodash/lodash.js' }
npm http 200 https://registry.npmjs.org/uid2/-/uid2-0.0.2.tgz
npm http 200 https://registry.npmjs.org/qs/-/qs-0.6.5.tgz
npm http 200 https://registry.npmjs.org/multiparty/-/multiparty-2.2.0.tgz
npm http 200 https://registry.npmjs.org/negotiator/-/negotiator-0.2.8.tgz
npm http 200 https://registry.npmjs.org/bytes/-/bytes-0.2.0.tgz
npm http 200 https://registry.npmjs.org/raw-body/-/raw-body-0.0.3.tgz
npm http 200 https://registry.npmjs.org/pause/-/pause-0.0.1.tgz
npm http GET https://registry.npmjs.org/graceful-fs
npm http GET https://registry.npmjs.org/abbrev
npm http 200 https://registry.npmjs.org/graceful-fs
npm http 200 https://registry.npmjs.org/abbrev
npm http GET https://registry.npmjs.org/graceful-fs/-/graceful-fs-1.1.14.tgz
npm http GET https://registry.npmjs.org/abbrev/-/abbrev-1.0.4.tgz
npm http 200 https://registry.npmjs.org/graceful-fs/-/graceful-fs-1.1.14.tgz
npm http 200 https://registry.npmjs.org/abbrev/-/abbrev-1.0.4.tgz
npm http GET https://registry.npmjs.org/wordwrap
npm http 200 https://registry.npmjs.org/wordwrap
npm http GET https://registry.npmjs.org/wordwrap/-/wordwrap-0.0.2.tgz
npm http 200 https://registry.npmjs.org/wordwrap/-/wordwrap-0.0.2.tgz
npm http GET https://registry.npmjs.org/underscore.string
npm http 304 https://registry.npmjs.org/underscore.string
npm http GET https://registry.npmjs.org/underscore.string/-/underscore.string-2.3.3.tgz
npm http GET https://registry.npmjs.org/source-map
npm http GET https://registry.npmjs.org/async
npm http 200 https://registry.npmjs.org/underscore.string/-/underscore.string-2.3.3.tgz
npm http 304 https://registry.npmjs.org/async
npm http 200 https://registry.npmjs.org/source-map
npm http GET https://registry.npmjs.org/source-map/-/source-map-0.1.30.tgz
npm http 200 https://registry.npmjs.org/source-map/-/source-map-0.1.30.tgz
npm http GET https://registry.npmjs.org/cssom
npm http GET https://registry.npmjs.org/mkdirp
npm http 304 https://registry.npmjs.org/mkdirp
npm http 304 https://registry.npmjs.org/cssom
npm http GET https://registry.npmjs.org/amdefine
npm http 200 https://registry.npmjs.org/amdefine
npm http GET https://registry.npmjs.org/amdefine/-/amdefine-0.1.0.tgz
npm http 200 https://registry.npmjs.org/amdefine/-/amdefine-0.1.0.tgz
npm http GET https://registry.npmjs.org/readable-stream
npm http GET https://registry.npmjs.org/stream-counter
npm http 200 https://registry.npmjs.org/stream-counter
npm http GET https://registry.npmjs.org/stream-counter/-/stream-counter-0.2.0.tgz
npm http 200 https://registry.npmjs.org/readable-stream
npm http GET https://registry.npmjs.org/readable-stream/-/readable-stream-1.1.9.tgz
npm http 200 https://registry.npmjs.org/stream-counter/-/stream-counter-0.2.0.tgz
npm http 200 https://registry.npmjs.org/readable-stream/-/readable-stream-1.1.9.tgz
npm http GET https://registry.npmjs.org/core-util-is
npm http GET https://registry.npmjs.org/debuglog/0.0.2
npm http 200 https://registry.npmjs.org/core-util-is
npm http 200 https://registry.npmjs.org/debuglog/0.0.2
npm http GET https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.0.tgz
npm http GET https://registry.npmjs.org/debuglog/-/debuglog-0.0.2.tgz
npm http 200 https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.0.tgz
npm http 200 https://registry.npmjs.org/debuglog/-/debuglog-0.0.2.tgz
npm http GET https://registry.npmjs.org/send/0.1.0
npm http GET https://registry.npmjs.org/cookie/0.0.5
npm http GET https://registry.npmjs.org/cookie-signature/0.0.1
npm http GET https://registry.npmjs.org/buffer-crc32/0.1.1
npm http GET https://registry.npmjs.org/fresh/0.1.0
npm http GET https://registry.npmjs.org/connect/2.7.2
npm http GET https://registry.npmjs.org/commander/0.6.1
npm http GET https://registry.npmjs.org/methods/0.0.1
npm http GET https://registry.npmjs.org/range-parser/0.0.4
npm http GET https://registry.npmjs.org/mkdirp/0.3.3
npm http 200 https://registry.npmjs.org/cookie/0.0.5
npm http 200 https://registry.npmjs.org/fresh/0.1.0
npm http 200 https://registry.npmjs.org/send/0.1.0
npm http 200 https://registry.npmjs.org/buffer-crc32/0.1.1
npm http 200 https://registry.npmjs.org/cookie-signature/0.0.1
npm http GET https://registry.npmjs.org/cookie/-/cookie-0.0.5.tgz
npm http GET https://registry.npmjs.org/fresh/-/fresh-0.1.0.tgz
npm http GET https://registry.npmjs.org/send/-/send-0.1.0.tgz
npm http GET https://registry.npmjs.org/buffer-crc32/-/buffer-crc32-0.1.1.tgz
npm http GET https://registry.npmjs.org/cookie-signature/-/cookie-signature-0.0.1.tgz
npm http 304 https://registry.npmjs.org/commander/0.6.1
npm http 304 https://registry.npmjs.org/methods/0.0.1
npm http 304 https://registry.npmjs.org/range-parser/0.0.4
npm http 304 https://registry.npmjs.org/mkdirp/0.3.3
npm http 200 https://registry.npmjs.org/connect/2.7.2
npm http GET https://registry.npmjs.org/connect/-/connect-2.7.2.tgz
npm http 200 https://registry.npmjs.org/cookie/-/cookie-0.0.5.tgz
npm http 200 https://registry.npmjs.org/send/-/send-0.1.0.tgz
npm http 200 https://registry.npmjs.org/fresh/-/fresh-0.1.0.tgz
npm http 200 https://registry.npmjs.org/connect/-/connect-2.7.2.tgz
npm http 200 https://registry.npmjs.org/buffer-crc32/-/buffer-crc32-0.1.1.tgz
npm http 200 https://registry.npmjs.org/cookie-signature/-/cookie-signature-0.0.1.tgz
npm http GET https://registry.npmjs.org/mime/1.2.6
npm http 200 https://registry.npmjs.org/mime/1.2.6
npm http GET https://registry.npmjs.org/mime/-/mime-1.2.6.tgz
npm http 200 https://registry.npmjs.org/mime/-/mime-1.2.6.tgz
npm http GET https://registry.npmjs.org/formidable/1.0.11
npm http GET https://registry.npmjs.org/bytes/0.1.0
npm http GET https://registry.npmjs.org/pause/0.0.1
npm http 304 https://registry.npmjs.org/pause/0.0.1
npm http 200 https://registry.npmjs.org/formidable/1.0.11
npm http GET https://registry.npmjs.org/formidable/-/formidable-1.0.11.tgz
npm http 200 https://registry.npmjs.org/bytes/0.1.0
npm http GET https://registry.npmjs.org/bytes/-/bytes-0.1.0.tgz
npm http 200 https://registry.npmjs.org/formidable/-/formidable-1.0.11.tgz
npm http 200 https://registry.npmjs.org/bytes/-/bytes-0.1.0.tgz
npm ERR! Error: UNKNOWN, mkdir '/home/website/nodejs/rendr-try2/rendr-app-template/node_modules/rendr-handlebars/node_modules/rendr/node_modules/
express/node_modules/connect/node_modules/formidable/test/fixture/http/special-chars-in-filename'
npm ERR! If you need help, you may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com

npm ERR! System Linux 3.2.0-23-generic-pae
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /home/website/nodejs/rendr-try2/rendr-app-template
npm ERR! node -v v0.10.21
npm ERR! npm -v 1.3.11
npm ERR! path /home/website/nodejs/rendr-try2/rendr-app-template/node_modules/rendr-handlebars/node_modules/rendr/node_modules/express/node_modul
es/connect/node_modules/formidable/test/fixture/http/special-chars-in-filename
npm ERR! fstream_path /home/website/nodejs/rendr-try2/rendr-app-template/node_modules/rendr-handlebars/node_modules/rendr/node_modules/express/no
de_modules/connect/node_modules/formidable/test/fixture/http/special-chars-in-filename/info.md
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code UNKNOWN
npm ERR! errno -1
npm ERR! fstream_stack /usr/lib/node_modules/npm/node_modules/fstream/lib/writer.js:171:23
npm ERR! fstream_stack /usr/lib/node_modules/npm/node_modules/mkdirp/index.js:37:53
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: EPERM, open '/home/website/nodejs/rendr-try2/rendr-app-template/node_modules/rendr-handlebars/node_modules/rendr/node_modules/npm
/node_modules/read-package-json/node_modules/normalize-package-data/test/fixtures/node-module_exist.json'
npm ERR!  { [Error: EPERM, open '/home/website/nodejs/rendr-try2/rendr-app-template/node_modules/rendr-handlebars/node_modules/rendr/node_modules
/npm/node_modules/read-package-json/node_modules/normalize-package-data/test/fixtures/node-module_exist.json']
npm ERR!   errno: 50,
npm ERR!   code: 'EPERM',
npm ERR!   path: '/home/website/nodejs/rendr-try2/rendr-app-template/node_modules/rendr-handlebars/node_modules/rendr/node_modules/npm/node_modul
es/read-package-json/node_modules/normalize-package-data/test/fixtures/node-module_exist.json' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Linux 3.2.0-23-generic-pae
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /home/website/nodejs/rendr-try2/rendr-app-template
npm ERR! node -v v0.10.21
npm ERR! npm -v 1.3.11
npm ERR! path /home/website/nodejs/rendr-try2/rendr-app-template/node_modules/rendr-handlebars/node_modules/rendr/node_modules/npm/node_modules/r
ead-package-json/node_modules/normalize-package-data/test/fixtures/node-module_exist.json
npm ERR! code EPERM
npm ERR! errno 50
npm ERR! stack Error: EPERM, open '/home/website/nodejs/rendr-try2/rendr-app-template/node_modules/rendr-handlebars/node_modules/rendr/node_modul
es/npm/node_modules/read-package-json/node_modules/normalize-package-data/test/fixtures/node-module_exist.json'
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/website/nodejs/rendr-try2/rendr-app-template/npm-debug.log
npm ERR! not ok code 0
vagrant@precise32:/home/website/nodejs/rendr-try2/rendr-app-template$

Anyone have any ideas what's going on here ?

**Comment by spikebrehm** [comment]
Looks like some EPERMs and issues creating symlinks?  This is probably an issue with the way NPM is interacting with your system, not with rendr-app-template.

Try upgrading to latest NPM?  Make sure you don't need to run as sudo?

BTW, this repo is being deprecated in favor of the `examples` directory in `airbnb/rendr`:

https://github.com/airbnb/rendr/tree/master/examples

**Comment by haknick** [comment]
Thanks a lot for the quick reply.

**Comment by haknick** [comment]
Figured it out. This issue can be closed. It was an issue with how node was being installed and the paths. The simplest way is to install node using nvm. Installing node without sudo and working with the paths works too.
