### ISSUE TITLE
Need to add  "npm install" step to README

### ISSUE THREAD

**Issue by adeleinr** [rendrjs/rendr-app-template#8]
Hi Spike,

For those who are Node noobs like me, it may be useful to add a step that indicates to run "npm install" inside the rendr-app-template folder right before running grunt server to install all the projects requirements. Also, I think a step for "npm install grunt --save-dev" is probably needed too? I had to use both of those steps. Great work btw!

**Comment by spikebrehm** [comment]
Thanks, good call! Don't know how I missed that. commit: https://github.com/airbnb/rendr-app-template/commit/98c9259585ddfdb035c8692ee457fa947111b7a7
