### ISSUE TITLE
Unable to start server in Windows 7

### ISSUE THREAD

**Issue by mattbroekhuis** [rendrjs/rendr-app-template#9]
I did the entire process correctly on my mac laptop, however when I try to follow the instructions on my windows 7 machine I get an error when running grunt. What am I doing wrong?

![image](https://f.cloud.github.com/assets/1326836/355128/e82eaa32-a0c8-11e2-8556-3d10a34f6870.png)

**Comment by spikebrehm** [comment]
Oh interesting, that's coming from the `DEBUG=app:*` environment variable set here: https://github.com/airbnb/rendr-app-template/blob/master/Gruntfile.js#L14. It's used by TJ's useful `debug` module: https://github.com/visionmedia/debug

How does one set environment variables on Windows?  For now I'll just take that out; it's not strictly needed.

**Comment by spikebrehm** [comment]
See: https://github.com/airbnb/rendr-app-template/commit/e3a162fefb2ab1cfec13b4bdb8ebb1e22948f93c

**Comment by mattbroekhuis** [comment]
Now I get this. I suppose it is related to grunt on windows. I would just switch to Linux, but i have 3 monitors and two video cards, and that is a living nightmare to setup apparently.

![image](https://f.cloud.github.com/assets/1326836/355417/40573f3e-a0d9-11e2-9bc4-83cd78b54076.png)
